from enum import StrEnum


class MessageCategory(StrEnum):
    DAMAGE_CHARGE_REQUIRED = "DAMAGE_CHARGE_REQUIRED"
    DAMAGE_NO_CHARGE_REQUIRED = "DAMAGE_NO_CHARGE_REQUIRED"
    SERVICE_IGNORED = "SERVICE_IGNORED"
    CLEANING_IGNORED = "CLEANING_IGNORED"
    INFO_IGNORED = "INFO_IGNORED"


class CaseStatus(StrEnum):
    WAITING_FOR_RETURN = "WAITING_FOR_RETURN"
    WAITING_MANAGER_ACTION = "WAITING_MANAGER_ACTION"
    REMINDER_1_SENT = "REMINDER_1_SENT"
    REMINDER_2_SENT = "REMINDER_2_SENT"
    REMINDER_3_SENT = "REMINDER_3_SENT"
    MANAGER_SEEN = "MANAGER_SEEN"
    WAITING_CLOSE_COMMENT = "WAITING_CLOSE_COMMENT"
    WAITING_SERVICE_AMOUNT = "WAITING_SERVICE_AMOUNT"
    CLOSED_PAID_CASH = "CLOSED_PAID_CASH"
    CLOSED_BALANCE_CHARGED = "CLOSED_BALANCE_CHARGED"
    CLOSED_INSTALLMENT = "CLOSED_INSTALLMENT"
    CLOSED_PERIODIC_CHARGES = "CLOSED_PERIODIC_CHARGES"
    CLOSED_TRANSFERRED_TO_OFFICE = "CLOSED_TRANSFERRED_TO_OFFICE"
    CLOSED_NO_CHARGE_REQUIRED = "CLOSED_NO_CHARGE_REQUIRED"
    CLOSED_NO_CHARGE_WITH_REASON = "CLOSED_NO_CHARGE_WITH_REASON"
    SERVICE_IGNORED = "SERVICE_IGNORED"
    CLEANING_IGNORED = "CLEANING_IGNORED"
    INFO_IGNORED = "INFO_IGNORED"
    AMBIGUOUS_CAR = "AMBIGUOUS_CAR"
    UNKNOWN_CAR = "UNKNOWN_CAR"
    ESCALATED_TO_SUPERVISOR = "ESCALATED_TO_SUPERVISOR"


class ActionType(StrEnum):
    CREATED_FROM_FP = "CREATED_FROM_FP"
    MATCHED_WITH_PV_RETURN = "MATCHED_WITH_PV_RETURN"
    REMINDER_SENT = "REMINDER_SENT"
    MANAGER_SEEN = "MANAGER_SEEN"
    CLOSE_REQUESTED = "CLOSE_REQUESTED"
    SERVICE_AMOUNT_REQUESTED = "SERVICE_AMOUNT_REQUESTED"
    SERVICE_AMOUNT_RECEIVED = "SERVICE_AMOUNT_RECEIVED"
    CLOSED_WITH_COMMENT = "CLOSED_WITH_COMMENT"
    CLOSED_NO_CHARGE_REQUIRED = "CLOSED_NO_CHARGE_REQUIRED"
    ESCALATED = "ESCALATED"


FINAL_STATUSES = {
    CaseStatus.CLOSED_PAID_CASH,
    CaseStatus.CLOSED_BALANCE_CHARGED,
    CaseStatus.CLOSED_INSTALLMENT,
    CaseStatus.CLOSED_PERIODIC_CHARGES,
    CaseStatus.CLOSED_TRANSFERRED_TO_OFFICE,
    CaseStatus.CLOSED_NO_CHARGE_REQUIRED,
    CaseStatus.CLOSED_NO_CHARGE_WITH_REASON,
    CaseStatus.SERVICE_IGNORED,
    CaseStatus.CLEANING_IGNORED,
    CaseStatus.INFO_IGNORED,
    CaseStatus.AMBIGUOUS_CAR,
    CaseStatus.UNKNOWN_CAR,
    CaseStatus.ESCALATED_TO_SUPERVISOR,
}

